### ISSUE TITLE
Identity File selection field seems to be ignored

### ISSUE THREAD

**Issue by Brade** [psequel/psequel#58]
Trying to connect to a standard vagrant box via SSH that has Ubuntu 14.04.3 and Postgres 9.3.9 installed. My host system is OSX 10.10.5

When I select the key file that vagrant uses by default, I get an error box that indicates PSequel tried to use standard key file locations like ~/.ssh/id_rsa instead of the one I selected: /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/keys/vagrant

I have tried using PSequel 1.1.2 as well as beta 1.2.4
Screenshot is attached.
![psequelssh](https://cloud.githubusercontent.com/assets/46009/9467977/1eb16ce8-4b0d-11e5-8be2-21fbd3327ec6.png)

**Comment by psequel** [comment]
Works fine for me. See screenshot for my settings.
<img width="717" alt="screen shot 2015-08-25 at 10 47 40 pm" src="https://cloud.githubusercontent.com/assets/10246639/9486397/75895df0-4b7b-11e5-9b28-e9a2e5379250.png">

Alternatively, you could set up port forwarding in your `Vagrantfile` with something like `config.vm.network "forwarded_port", guest: 5432, host: 15432`. Then you can connect to your database via localhost:15432.

Note that by default, postgres server listens on localhost only, so you will need to add `host all all all password` to `/etc/postgresql/9.3/main/pg_hba.conf` and `listen_addresses = '*'` to `/etc/postgresql/9.3/main/postgresql.conf`.

**Comment by Brade** [comment]
Grr, still not working even though I updated the location of Identity File to the different (correct) one. This command line method works fine:

ssh -i /path/to/virtualbox/private_key vagrant@192.168.33.10

So I'm at a loss for why it fails in Psequel.

**Comment by psequel** [comment]
hmm..I have no idea why it's not working for you. Basically PSequel is running `ssh user@sshHost -i /path/to/private_key -v -N -L localPort:remoteHost:remotePort -o ExitOnForwardFailure=yes -o TCPKeepAlive=no -o ServerAliveInterval=60` in the background.

Maybe try deleting that connection and create a new one?

**Comment by Brade** [comment]
Got a straight-up crash on the beta version. Tried the stable release and got the same error. It's weird b/c I'm not the type of person to install a bunch of weird crap on my computer (so I can avoid situations like this). I consider it a typical setup.

**Comment by nasdf** [comment]
I was able to fix the same issue by using a relative path `~/Documents/Projects/key.pem` instead of an absolute path `/Users/Me/Documents/Projects/key.pem`.  Hope this helps.

**Comment by psequel** [comment]
V1.2.5.beta uses a slightly different command to setup SSH tunneling. Please try it out and let me know if it works for you.

**Comment by Brade** [comment]
still crashes =(   I'm sending the crash report output to your support email.

**Comment by spencerwi** [comment]
I'm also getting a straight crash on v1.2.6 final, but only for new connections.

I have a saved connection that I created using v1.1, and it works fine. So basically I can have exactly one working SSH-tunneled connection that I have to constantly tweak to connect to various dbs.

**Comment by psequel** [comment]
@spencerwi could you try v1.2.7?

**Comment by spencerwi** [comment]
@psequel No longer crashes. Thanks!

**Comment by psequel** [comment]
@Brade what about you? Is the latest version still crashing on you?

**Comment by Brade** [comment]
Sadly... yeah. Just tried 1.3.0. On a new laptop even. 
I can connect fine w/ pgAdmin. So not sure what the deal is.
One thing I thought of is that I have NFS enabled on Vagrant settings, which is recommended to speed up the VM: https://docs.vagrantup.com/v2/synced-folders/nfs.html 
That's the only setting I changed from the default, so that might be a factor, but I'm not sure.

**Comment by psequel** [comment]
Hmm...if you think NFS could be a problem, could you try disabling it temporarily to see if it changes anything?

**Comment by reganjohnson** [comment]
I can confirm that the identity file is being ignored also. There is no mention of the file in the output log.

I solved the problem by copying the vagrant generated id_rsa to ~/.ssh/id_dsa (which is being checked by PSequel automatically).

**Comment by dondeng** [comment]
Same here.. identity file is being ignored. I'm on version 1.3.5. For now I'm using the same workaround mentioned by @reganjohnson  above..

**Comment by mikoim** [comment]
Same. I'm on version 1.4.2. 
It seems that 'Identity File' field is ignored and try to load private key based on ```~/.ssh/ssh_config```.

```
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/USER_NAME/.ssh/config
debug1: /Users/USER_NAME/.ssh/config line 9: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.56.101 [192.168.56.101] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /Users/USER_NAME/.ssh/WRONG_KEY.key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/USER_NAME/.ssh/WRONG_KEY.key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.9p1 Ubuntu-2ubuntu0.1
debug1: match: OpenSSH_6.9p1 Ubuntu-2ubuntu0.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.56.101:22 as 'USER_NAME'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HOGEHOGE
debug1: read_passphrase: can't open /dev/tty: Device not configured
Host key verification failed.
```

**Comment by psequel** [comment]
Fixed in v1.4.3. Credit to [this comment](https://github.com/psequel/psequel/issues/7#issuecomment-172818095).

**Comment by shutchinson** [comment]
Unfortunately I am still having this issue.

```
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.10.10 [192.168.10.10] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /Users/shutch/Desktop/dev/quoter-dev-box/.vagrant/machines/default/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/shutch/Desktop/dev/quoter-dev-box/.vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to 192.168.10.10:22 as 'vagrant'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:RoUZaB2lOo+bdl8nmOJyAY1nSYMVPumSSgoXH/KC0rA
debug1: read_passphrase: can't open /dev/tty: Device not configured
Host key verification failed.
```

![screen shot 2016-03-19 at 11 26 01 pm](https://cloud.githubusercontent.com/assets/188424/13902695/f8dcc880-ee29-11e5-8018-7e246daeee5d.png)


Any thoughts?

**Comment by psequel** [comment]
@shutchinson Looks like PSequel is trying to use the identity file you provided.

> debug1: identity file /Users/shutch/Desktop/dev/quoter-dev-box/.vagrant/machines/default/virtualbox/private_key type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /Users/shutch/Desktop/dev/quoter-dev-box/.vagrant/machines/default/virtualbox/private_key-cert type -1

And if a passphrase is associated with the identity file, see the text just below the "identity file" field...
