### ISSUE TITLE
no connection to the server error

### ISSUE THREAD

**Issue by scttcper** [psequel/psequel#67]
Hi again!

Running into an issue with the latest version: 1.2.6
I've returned to v1.1.2 to confirm my settings and everything is working on that version.

On v1.2.6 it opens the connection, but when I click on a table to view its content it beachballs and then shows up with the error attached.
![screen shot 2015-10-13 at 11 30 14 am](https://cloud.githubusercontent.com/assets/1400464/10464281/d3d59d0e-719d-11e5-986e-5eea3a5e9422.png)

This happens with any table on this remote connection. I can also confirm that psequel does work with a local database of the same structure (different but similar data).

The only interesting thing I see in our connection settings is that our password has a "(" in it and I cannot change this to test. I'm on osx 10.10.5

**Comment by rdp** [comment]
how about 1.3.0?

**Comment by psequel** [comment]
@scttcper could you try v1.3.1? I just fixed a bug that causes connection failures if the password contains special characters.

**Comment by scttcper** [comment]
Sorry about the delay was out of office. Still not working on v1.3.2 :frowning: 
Got a crash on my first attempt and on all attempts now I get this error message.
<img width="429" alt="screen shot 2015-10-26 at 11 33 04 am" src="https://cloud.githubusercontent.com/assets/1400464/10738591/5f600530-7bd5-11e5-891a-d490c39d304d.png">

This gist contains the report from the crash.
https://gist.github.com/scttcper/64328110978978237233

**Comment by psequel** [comment]
A "connection dead" error usually means the connection was killed either by the server or on the client side. Have you tried the app on a stable connection?

**Comment by scttcper** [comment]
Just tried using work's gigabit connection. Is there any way to view a log of the queries psequel is attempting against the server so I could try them with cli or something. Let me know of anything else you'd like me to try.

video of error:
https://www.youtube.com/watch?v=RmlwNHwFgcc

**Comment by psequel** [comment]
If you have access to the PostgreSQL server, you could turn on statement logs and tail the log file.

**Comment by scttcper** [comment]
this was caused by settings on our postgres server using docker. Not sure which ones, but on a new server the issue is resolved.

**Comment by psequel** [comment]
@scttcper glad to hear that you solved the problem. Could you please update this post if later you figure out which setting was causing the problem?
